/**
 * @module commands/init/generators/pr-template
 * @description GitHub Pull Request Template generator for auto-fix workflow
 */

import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import type { Result } from '../../../common/types/index.js';
import { ok, err } from '../../../common/types/index.js';

/**
 * PR template content for auto-fix workflow
 */
const PR_TEMPLATE_CONTENT = `## Description

<!-- Briefly describe what this PR does -->

## Related Issues

<!-- Link related issues using "Fixes #123" or "Closes #123" -->
- Fixes #

## Type of Change

- [ ] 🐛 Bug fix (non-breaking change that fixes an issue)
- [ ] ✨ New feature (non-breaking change that adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 📝 Documentation update
- [ ] 🔧 Refactoring (no functional changes)
- [ ] 🤖 Auto-generated by auto-fix-workflow

## Changes Made

<!-- List the main changes in this PR -->
-
-
-

## Testing

<!-- Describe how you tested these changes -->
- [ ] Unit tests pass
- [ ] Type check passes
- [ ] Lint passes
- [ ] Manual testing performed

## Checklist

- [ ] My code follows the project's coding standards
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published

## Screenshots (if applicable)

<!-- Add screenshots to help explain your changes -->

## Additional Notes

<!-- Any additional information that reviewers should know -->
`;

/**
 * Check if PR template already exists
 */
export async function prTemplateExists(projectRoot: string): Promise<boolean> {
  const templatePath = join(projectRoot, '.github', 'PULL_REQUEST_TEMPLATE.md');
  try {
    await fs.access(templatePath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Write GitHub PR Template for auto-fix workflow
 *
 * @param projectRoot - Project root path
 * @returns Result indicating success or failure
 */
export async function writePRTemplate(
  projectRoot: string
): Promise<Result<boolean, Error>> {
  const githubDir = join(projectRoot, '.github');
  const templatePath = join(githubDir, 'PULL_REQUEST_TEMPLATE.md');

  try {
    // Create .github directory if it doesn't exist
    await fs.mkdir(githubDir, { recursive: true });

    // Write the template file
    await fs.writeFile(templatePath, PR_TEMPLATE_CONTENT, 'utf-8');

    return ok(true);
  } catch (error) {
    return err(
      error instanceof Error
        ? error
        : new Error(`Failed to write PR template: ${String(error)}`)
    );
  }
}
