/**
 * @module workflow/code-fix-strategy/constants
 * @description Constants and default values for fix strategy
 */

/**
 * Default maximum retry attempts
 */
export const DEFAULT_MAX_RETRIES = 3;

/**
 * Default forbidden patterns - dangerous operations that should never be in automated fixes
 */
export const FORBIDDEN_PATTERNS = [
  // Dangerous shell commands
  'rm -rf',
  'rm -fr',
  'del /s',
  'deltree',
  'format c:',

  // Dangerous SQL operations
  'DROP TABLE',
  'DROP DATABASE',
  'TRUNCATE TABLE',
  'DELETE FROM .* WHERE 1=1',

  // Dangerous file operations
  'unlink',
  'rmdir',
  'fs.rmdirSync',
  'fs.unlinkSync',

  // Credential patterns
  'password\\s*=',
  'api[_-]?key\\s*=',
  'secret\\s*=',
  'token\\s*=',
  'private[_-]?key\\s*=',

  // Dangerous Node.js operations
  'child_process.exec',
  'eval\\(',
  'Function\\(',

  // Environment variable exposure
  'process.env.PASSWORD',
  'process.env.SECRET',
  'process.env.API_KEY',

  // Dangerous Git operations
  'git reset --hard',
  'git push --force',
  'git clean -fd',

  // Disable security features
  'ssl.CERT_NONE',
  'verify=False',
  'rejectUnauthorized.*false',

  // Debug/test code that should not be committed
  'debugger;',
  'console.log\\(.*password',
  'console.log\\(.*secret',
  'console.log\\(.*token',
] as const;

/**
 * Default allowed scopes - directories that are safe to modify
 */
export const DEFAULT_ALLOWED_SCOPES = [
  'src/',
  'lib/',
  'app/',
  'components/',
  'utils/',
  'helpers/',
  'services/',
  'pages/',
  'views/',
  'tests/',
  '__tests__/',
  'spec/',
] as const;

/**
 * Maximum number of files that can be changed in a single fix
 */
export const MAX_FILES_PER_FIX = 20;

/**
 * Maximum number of directories that can be affected
 */
export const MAX_DIRECTORIES_PER_FIX = 5;

/**
 * Commit message template
 */
export const COMMIT_MESSAGE_TEMPLATE = `{type}: {description}

{body}

Fixes #{issueNumbers}
`;

/**
 * PR title template
 */
export const PR_TITLE_TEMPLATE = '{type}: {description}';

/**
 * PR body template
 */
export const PR_BODY_TEMPLATE = `## Summary
{summary}

## Changes
{changes}

## Issues
{issues}

## Checklist
- [ ] Tests pass
- [ ] Type checks pass
- [ ] Linting passes
- [ ] No forbidden patterns detected

---
Auto-generated by auto-fix-workflow
`;
